"""Git-tracked YAML-Snapshots der aktuell aktiven Parameter-Versionen.

Zweck
-----

Das hash-chained ``parameter_journal.jsonl`` ist Audit-Wahrheit, aber aus
Operator-Sicht unhandlich:

- es muss für jeden Lookup von vorn nach hinten geparst werden,
- es zeigt keinen Diff "was hat sich materiell geändert" im Code-Review,
- es ist nicht git-tracked (lebt unter ``artifacts/``).

Diese Schicht spiegelt nach jedem Approval/Rollback den aktuell aktiven
``parameter_set`` als YAML unter ``config/learning/<sanitized_path>.yaml``
ab. Der Snapshot ist:

- **derivativ** — die JSONL-Kette bleibt source-of-truth für Tampering-
  Detection. Der Snapshot ist nur eine bequeme Sicht.
- **stamped** — Header trägt ``version_id``, ``activated_at_utc``,
  ``activated_by`` für Audit-Spur.
- **git-trackbar** — Operator sieht echte Diffs zwischen Versionen im PR.

Konvention
----------

Boot-Loader (RiskEngine/SignalGenerator) lesen den YAML-Snapshot. Wenn
kein Snapshot existiert: kein Calibrator aktiv (Identity-Verhalten). Damit
ist ein frisches System verhalten-erhaltend (kein Bias durch Geister-
Werte).
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

import yaml  # type: ignore[import-untyped]

logger = logging.getLogger(__name__)

DEFAULT_SNAPSHOT_DIR: Final[Path] = Path("config/learning")

# Allowed characters in path → filename. Everything else becomes underscore.
_FILENAME_SAFE_RE: Final[re.Pattern[str]] = re.compile(r"[^A-Za-z0-9._-]+")

_HEADER_NOTICE: Final[str] = (
    "# Auto-generated by KAI learning approval pipeline.\n"
    "# DO NOT EDIT MANUALLY — changes are overwritten on next approval.\n"
    "# Source of truth: artifacts/learning/parameter_journal.jsonl\n"
)


@dataclass(frozen=True)
class ConfigSnapshot:
    """A loaded YAML snapshot — content + metadata."""

    parameter_path: str
    version_id: str
    activated_at_utc: str
    activated_by: str
    parameter_set: dict[str, Any]


def snapshot_path(parameter_path: str, snapshot_dir: Path | str) -> Path:
    """Translate a dotted parameter_path into a YAML filename within `snapshot_dir`.

    Sanitizes filename-unsafe characters to underscore. Empty paths raise.
    """
    if not parameter_path or not parameter_path.strip():
        raise ValueError("parameter_path must be non-empty")
    safe = _FILENAME_SAFE_RE.sub("_", parameter_path.strip())
    return Path(snapshot_dir) / f"{safe}.yaml"


def write_snapshot(
    *,
    parameter_path: str,
    parameter_set: dict[str, Any],
    version_id: str,
    activated_at_utc: str,
    activated_by: str,
    snapshot_dir: Path | str,
) -> Path:
    """Write a YAML snapshot atomically (tmp-file + rename)."""
    target = snapshot_path(parameter_path, snapshot_dir)
    target.parent.mkdir(parents=True, exist_ok=True)

    payload: dict[str, Any] = {
        "parameter_path": parameter_path,
        "version_id": version_id,
        "activated_at_utc": activated_at_utc,
        "activated_by": activated_by,
        "parameter_set": parameter_set,
    }
    body = yaml.safe_dump(
        payload,
        sort_keys=True,
        allow_unicode=True,
        default_flow_style=False,
    )

    # Atomic write: tmp + os.replace
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(_HEADER_NOTICE + body, encoding="utf-8")
    tmp.replace(target)
    logger.info("[learning-snapshot] wrote %s (version_id=%s)", target, version_id)
    return target


def read_snapshot(
    parameter_path: str, snapshot_dir: Path | str
) -> ConfigSnapshot | None:
    """Read a YAML snapshot. Returns None if missing or malformed.

    Malformed files are logged + skipped — they never crash the boot path.
    """
    path = snapshot_path(parameter_path, snapshot_dir)
    if not path.exists():
        return None
    try:
        raw = path.read_text(encoding="utf-8")
        payload = yaml.safe_load(raw)
    except (OSError, yaml.YAMLError) as exc:
        logger.warning("[learning-snapshot] failed to read %s: %s", path, exc)
        return None
    if not isinstance(payload, dict):
        logger.warning("[learning-snapshot] %s is not a YAML mapping — ignoring", path)
        return None
    try:
        return ConfigSnapshot(
            parameter_path=str(payload["parameter_path"]),
            version_id=str(payload["version_id"]),
            activated_at_utc=str(payload["activated_at_utc"]),
            activated_by=str(payload["activated_by"]),
            parameter_set=dict(payload.get("parameter_set") or {}),
        )
    except (KeyError, TypeError, ValueError) as exc:
        logger.warning(
            "[learning-snapshot] %s is missing required fields: %s",
            path,
            exc,
        )
        return None


def remove_snapshot(parameter_path: str, snapshot_dir: Path | str) -> bool:
    """Delete a snapshot file. Returns True if removed, False if absent.

    Used by tests / explicit operator commands. Not auto-invoked on reject —
    rejecting a never-active proposal must NOT touch the active snapshot.
    """
    path = snapshot_path(parameter_path, snapshot_dir)
    if not path.exists():
        return False
    try:
        path.unlink()
    except OSError as exc:
        logger.warning("[learning-snapshot] failed to remove %s: %s", path, exc)
        return False
    return True


__all__ = [
    "DEFAULT_SNAPSHOT_DIR",
    "ConfigSnapshot",
    "read_snapshot",
    "remove_snapshot",
    "snapshot_path",
    "write_snapshot",
]
