"""Add LLMAuditRecord

Revision ID: 74fab3f5b5d5
Revises: 0007
Create Date: 2026-05-09 13:07:01.787194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fab3f5b5d5'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_audit_created_at'), 'llm_audit', ['created_at'], unique=False)
    op.create_index('ix_llm_audit_document_created', 'llm_audit', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_audit_document_id'), 'llm_audit', ['document_id'], unique=False)
    op.create_index('ix_canonical_documents_content_hash', 'canonical_documents', ['content_hash'], unique=True)
    op.create_index(op.f('ix_portfolio_states_created_at'), 'portfolio_states', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_states_symbol'), 'portfolio_states', ['symbol'], unique=False)
    op.create_index(op.f('ix_trading_cycles_created_at'), 'trading_cycles', ['created_at'], unique=False)
    op.create_index(op.f('ix_trading_cycles_symbol'), 'trading_cycles', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_cycles_symbol'), table_name='trading_cycles')
    op.drop_index(op.f('ix_trading_cycles_created_at'), table_name='trading_cycles')
    op.drop_index(op.f('ix_portfolio_states_symbol'), table_name='portfolio_states')
    op.drop_index(op.f('ix_portfolio_states_created_at'), table_name='portfolio_states')
    op.drop_index('ix_canonical_documents_content_hash', table_name='canonical_documents')
    op.drop_index(op.f('ix_llm_audit_document_id'), table_name='llm_audit')
    op.drop_index('ix_llm_audit_document_created', table_name='llm_audit')
    op.drop_index(op.f('ix_llm_audit_created_at'), table_name='llm_audit')
    op.drop_table('llm_audit')
    # ### end Alembic commands ###
